version: '3.7'

services:

    client:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        tty: true
        ports:
            - "3000:3000"
        volumes: 
            - ./frontend:/app
            - /app/node_modules
        networks:
            - frontend

    mongodb:
        image: mongo
        container_name: mongo
        restart: unless-stopped
        command: mongod --port 27017 --bind_ip 0.0.0.0
        environment:
            MONGO_INITDB_ROOT_USERNAME: "admin"
            MONGO_INITDB_ROOT_PASSWORD: "admin_password"
            MONGO_INITDB_DATABASE: "axx"
            MONGODB_DATA_DIR: /data/db
        volumes:
        - axx-db:/data/db
        networks:
        - backend

    api:
        build: 
            context: ./backend
            dockerfile: Dockerfile
        command: gunicorn -w 1 --bind 0.0.0.0:5000 --timeout 520 app.main:app
        ports:
            - "5000:5000"
        environment:
            MONGODB_HOST: "mongo"
            MONGODB_USERNAME: "user"
            MONGODB_PASSWORD: "password"
            MONGO_INITDB_DATABASE: "axx"
            MONGO_INITDB_ROOT_USERNAME: "admin"
            MONGO_INITDB_ROOT_PASSWORD: "admin_password"
            NEPTUNE_API_TOKEN:
        volumes:
            - files:/files
        depends_on: 
            - mongodb
        networks:
            - frontend
            - backend

networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge
volumes:
    axx-db:
        driver: local
    files:
        driver: local